# Generated by Django 3.1.5 on 2021-01-12 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '패스트캠퍼스 사용자', 'verbose_name_plural': '패스트캠퍼스 사용자'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='registeredTime',
        ),
        migrations.AddField(
            model_name='user',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='fastcampus_fcuser',
        ),
    ]
