# Generated by Django 3.1.5 on 2021-01-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210112_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '유저 정보', 'verbose_name_plural': '유저 정보'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='유저 정보 테이블',
        ),
    ]
